[package]
name = "bevy_multiplayer_platformer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_matchbox = "0.9.0"
bincode = "1.3.3"
serde = "1.0.203"

[profile.dev.package."*"]
opt-level = 3
